config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :path=>'',
                      :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                      :controllers=>{:registrations=>'registrations'}
  root 'pages#home'

  resources :users, only: [:show]
  resources :rooms do
    resources :reservations, only: [:create]
  end
  resources :photos

  get '/preload' => 'reservations#prelaod'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/, :show => '786>x447'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 75}
  validates :summary, presence: true, length: {maximum: 600}
  validates :address, presence: true
  validates :price, numericality: {only_integer: true, greater_than: 5}

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :reservations
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :fullname, presence:true, length: {maximum: 50}

         has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
        validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

        has_many :rooms
        has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

  protected
   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

   def destroy
      @photo = Photo.find(params[:id])
      room = @photo.room

      @photo.destroy

      @photos = Photo.where(room_id: room.id)

      respond_to :js
   end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/reservations_controller.rb
class reservationsController < ApplicationController

  before_action :authenticate_user!

  def preload
    room = Room.find(params[:room_id])
    today = Date.today
    reservations = room.reservations.where('start_date >= ? OR end_date >= ?', today, today)

    render json :reservations
  end

  def create
    @reservation = current_user.reservations.create(reservation_params)
    redirect_to @reservation.room, notice: "Votre réservation a été acceptée"
  end

  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total)
  end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

before_action :set_room, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]
before_action :require_same_user, only: [:edit, :update]

   def index
      @rooms = current_user.rooms
   end

   def new
      @room = current_user.rooms.build
   end

   def create
      @room = current_user.rooms.build(room_params)
      if @room.save
          if params[:images]
              params[:images].each do |i|
                  @room.photos.create(image: i)
              end
          end
          @photos = @room.photos
          redirect_to edit_room_path(@room), notice:"Votre annonce a été ajouté avec succès"
      else
          render :new
      end
   end

   def show
       @photos = @room.photos
   end

   def edit
       @photos = @room.photos
   end

   def update
       if @room.update(room_params)
           if params[:images]
              params[:images].each do |i|
                  @room.photos.create(image: i)
              end
          end
          @photos = @room.photos
          redirect_to edit_room_path(@room), notice:"Modification enregistrée..."
       else
           render :edit
       end
   end

private
    def set_room
        @room = Room.find(params[:id])
    end

    def room_params
       params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room,
       :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet, :is_shampoo,
       :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, :active)
    end

    def require_same_user
       if current_user.id != @room.user_id
           flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
           redirect_to root_path
       end
   end
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    if user.avatar.present?
      user.avatar.url
    else
      'default_image.png'
    end
  end

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'AirCnC', root_path, { :class=>"navbar-brand" } %>
    </div>
    <div id="navbar" class="navbar-collapse collapse right">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_room_path do %>
            <i class="fa fa-home fa-lg"></i> Devenez hôte
          <% end %>
        </li>
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Inscription', new_user_registration_path %></li>
          <li><%= link_to 'Connexion', new_user_session_path %></li>

        <% else %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %><%= current_user.fullname %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Mes voyages", root_path %></li>
              <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirCnC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <%= csrf_meta_tags %>

  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<%= render 'layouts/navigation' %>

<%= render 'shared/message' %>

<div class="container"><%= yield %></div>

</body>
</html>

app/views/pages/home.html.erb
<h2>Bienvenue sur notre première page</h2>

app/views/photos/_list.html.erb
<% if @photos %>
    <div class="row">
        <% @photos.each do |photo| %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading preview">
                    <%= image_tag photo.image.url() %>
                </div>
                <div class="panel-body">
                    <span class="pull-right">
                        <%= link_to photo, remote: true, method: :delete, data: {confirm: "Attention, vous allez supprimer cette photo"} do %>
                            <i class="fa fa-times fa-lg"></i>
                        <% end %>
                    </span>
                </div>
            </div>
        </div>
        <% end %>
    </div>

<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>

<div class="row">
  <div class="col-md-12 price_tag">
    <span>€<%= @room.price %></span>
    <span class="pull-right">Par nuit</span>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <label>Arrivée</label>
    <%= f.text_field :start_date, readonly: 'true', placeholder:'jj/mm/aaaa', class:'form-control' %>
  </div>
  <div class="col-md-6">
    <label>Départ</label>
    <%= f.text_field :end_date, readonly: 'true', placeholder:'jj/mm/aaaa', class:'form-control', disabled: 'true' %>
  </div>
</div>

<div id="preview" style="display: none">
  <table class="reservation-table">
    <tbody>
      <tr>
        <td>Nuit(s)</td>
        <td>
          <span id="reservation_days"></span></td>
      </tr>
      <tr>
        <td>Total</td>
        <td>
          <span id="reservation_sum"></span></td>
      </tr>
    </tbody>
  </table>
</div>

<%= f.hidden_field :room_id, value: @room.id %>
<%= f.hidden_field :price, value: @room.price %>
<%= f.hidden_field :total, id:'reservation_total' %>

<br>

<%= f.submit "Demande de réservation", class:"btn btn-primary wide" %>

<% end %>

<script>
function unavailable(date) {
  dmy = date.getDate() + "-" + (
    date.getMonth() + 1
  ) + "-" + date.getFullYear();
  return [$.inArray(dmy, unavailableDates) == -1];
}
$(function () {

  unavailableDates = [];

  $.ajax({
    url: '/preload',
    data: {
      'room_id': <%= @room.id %>
    },
    dataType: 'json',
    success: function (data) {
      $.each(data, function (arrID, arrValue) {
        for (var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
          unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
        }
      })

      $('#reservation_start_date').datepicker({
        dateFormat: 'dd-mm-yy',
        monthNames: [
          'Janvier',
          'Février',
          'Mars',
          'Avril',
          'Mai',
          'Juin',
          'Juillet',
          'Août',
          'Septembre',
          'Octobre',
          'Novembre',
          'Décembre'
        ],
        dayNamesMin: [
          'D',
          'L',
          'M',
          'M',
          'J',
          'V',
          'S'
        ],
        minDate: 0,
        maxDate: '3m',
        beforeShowDay: unavailable,
        onSelect: function (selected) {
          $('#reservation_end_date').datepicker("option", "minDate", selected);
          $('#reservation_end_date').attr('disabled', false);
        }
      });

      $('#reservation_end_date').datepicker({
        dateFormat: 'dd-mm-yy',
        monthNames: [
          'Janvier',
          'Février',
          'Mars',
          'Avril',
          'Mai',
          'Juin',
          'Juillet',
          'Août',
          'Septembre',
          'Octobre',
          'Novembre',
          'Décembre'
        ],
        dayNamesMin: [
          'D',
          'L',
          'M',
          'M',
          'J',
          'V',
          'S'
        ],
        minDate: 0,
        maxDate: '3m',
        beforeShowDay: unavailable,
        onSelect: function (selected) {
          $('#reservation_start_date').datepicker("option", "maxDate", selected);
        }
      });

    }
  });

});
</script>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Devenez hôte AirCnC
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @room, html: {multipart: true} do |f| %>
      <%= render 'shared/errors' %>

      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Genre d'habitation</label>
            <%= f.select :home_type, [["Maison","Maison"],["Appartement", "Appartement"], ["Bed & Breakfast", "Bed & breakfast"]], id: "home_type", prompt:"A sélectionner...", class:"form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Type de logement</label>
            <%= f.select :room_type, [["Logement entier","Logement entier"],["Chambre privée", "Chambre privée"], ["Chambre partagée", "Chambre partagée"]], prompt:"A sélectionner...", class:"form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Combien de voyageurs ?</label>
            <%= f.select :accomodate, [["1 voyageur",1],["2 voyageurs",2], ["3 voyageurs",3], ["4 voyageurs",4] ,["5 voyageurs",5], ["6 voyageurs",6]], prompt:"A sélectionner...", class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Chambres</label>
            <%= f.select :bed_room, [["1",1],["2",2], ["3",3], ["4",4]], prompt:"A sélectionner...", class:"form-control" %>
          </div>
        </div>
        <div class="col-md-4 select">
          <div class="form-group">
            <label>Salles de bain</label>
            <%= f.select :bath_room, [["1",1],["2",2], ["3",3], ["4",4]], prompt:"A sélectionner...", class:"form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <label>Donnez un nom au logement</label>
          <%= f.text_field :listing_name, placeholder:"Titre de l'annonce", class:"form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <label>Résumé</label>
          <%= f.text_area :summary, placeholder:"Décrivez le décor, l'ambiance, ce qui se trouve à proximité, etc...", class:"form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <label>Adresse</label>
          <%= f.text_field :address, placeholder:"Où est situé votre logement ?", class:"form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <span class="btn btn-default btn-file">
              <i class="fa fa-cloud-upload fa-lg"></i>
              Téléchargez vos photos !
              <%= file_field_tag "images[]", type: :file, multiple: true %>
            </span>
          </div>
        </div>
      </div>

      <div id="photos"><%= render 'photos/list' %></div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.check_box :is_wifi %>Wifi
          </div>
          <div class="form-group">
            <%= f.check_box :is_tv %>Télévision
          </div>
          <div class="form-group">
            <%= f.check_box :is_closet %>Penderie/Commode
          </div>
          <div class="form-group">
            <%= f.check_box :is_shampoo %>Shampoing
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.check_box :is_kitchen %>Cuisine
          </div>
          <div class="form-group">
            <%= f.check_box :is_breakfast %>Petit déjeuner, café, thé
          </div>
          <div class="form-group">
            <%= f.check_box :is_heating %>Chauffage
          </div>
          <div class="form-group">
            <%= f.check_box :is_air %>Climatisation
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label>Prix par nuit</label>
            <div class="input-group">
              <%= f.text_field :price, placeholder:"ex: 45€", class: "form-control" %>
              <div class="input-group-addon">€</div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.check_box :active %>
          Annonce active
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Je valide mon annonce", class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Mes annonces", rooms_path, class:"sidebar-link active" %>
      </li>
    </ul>

    </div>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Mes annonces
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
        <div class="row">
          <div class="col-md-2">
            <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
          </div>

          <div class="col-md-7">
            <h4><%= room.listing_name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "Mettre à jour", edit_room_path(room), class:"btn btn-primary" %>
          </div>
        </div>
        <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <!-- Photo principale de l'annonce -->
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @photos[0].image.url(), class:"img-responsive" if @photos.length >0 %>
      </div>
    </div>
    <br>
    <!-- Informations principales -->
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-3 text-center">
            <%= image_tag avatar_url(@room.user), class:'img-circle avatar-large' %>
            <br>
            <br>
            <%= @room.user.fullname %>
          </div>
          <div class="col-md-9">
            <h4><%= @room.listing_name %></h4>
            <%= @room.address %>
            <div class="row text-center row-space-1">
              <div class="col-sm-3">
                <i class="fa fa-home fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-users fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-bed fa-2x"></i>
              </div>
              <div class="col-sm-3">
                <i class="fa fa-bath fa-2x"></i>
              </div>
            </div>
            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type %>
              </div>
              <div class="col-sm-3">
                <%= @room.accomodate %>
                <%= @room.accomodate> 1 ? "Voyageurs" : "Voyageur" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bed_room %>
                <%= @room.bed_room> 1 ? "Lits" : "Lit" %>
              </div>
              <div class="col-sm-3">
                <%= @room.bath_room %>
                <%= @room.bath_room> 1 ? "Salles de bain" : "Salle de bain" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <!-- Formulaire de réservation -->
        <%= render 'reservations/form' %>
      </div>
    </div>

    <!-- Description -->
    <div class="row">
      <div class="col-md-12">
        <h2>A propos de ce logement</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>

    <!-- Equipements -->
    <div class="row">
      <div class="col-md-2">
        <p>Equipements</p>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <ul class="equipments">
              <li class="<%= 'text-line-through' if !@room.is_wifi %>">Wifi</li>
              <li class="<%= 'text-line-through' if !@room.is_tv %>">Télévision</li>
              <li class="<%= 'text-line-through' if !@room.is_closet %>">Penderie/Commode</li>
              <li class="<%= 'text-line-through' if !@room.is_shampoo %>">Shampooing</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="equipments">
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Cuisine</li>
              <li class="<%= 'text-line-through' if !@room.is_breakfast %>">Petit déjeuner</li>
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Chauffage</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Climatisation</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <% if @photos %>
            <% @photos.each do |photo| %>
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>" class="active"></li>
              </ol>
            <% end %>
          <% end %>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <% if @photos %>
              <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
              <% end %>
            <% end %>

          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Précédent</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Suivant</span>
          </a>
        </div>
      </div>
    </div>
    <!-- Google maps -->
    <div class="row">
            <div class="col-md-12">
                <div id="map"></div>

                <style>
                   #map {
                    height: 400px;
                    width: 100%;
                   }
                </style>

                <script>
                  function initMap() {
                    var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
                    var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15,
                      center: uluru
                    });
                    var marker = new google.maps.Marker({
                      position: uluru,
                      map: map
                    });
                  }
                </script>
                <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfleOySlHkVEeW6TYI3Ss_ydpsaS5gz2I&callback=initMap">
                </script>
            </div>
</div>

    <!-- Logements à proximité -->
    <h3>À proximité</h3>
    <div class="row">
      <% for room in @room.nearbys(2).limit(3) %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
          </div>
          <div class="panel-body">
            <%= link_to room.listing_name, room %><br>
            (à <%= (room.distance*1.6).round(2) %> km)
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>

<% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>
    <script type="text/javascript">
        <% @room.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>

<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>


<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag avatar_url(@user), class:"avatar-full" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        Vérification
      </div>
      <div class="panel-body">
        Email:
        <%= @user.email %><br>
        Tél:
        <%= @user.phone_number %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>

</div>